server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    reply:
      timeout: 15
    topic:
      replicationFactor: 1
      partitions: 1
      names:
        user-add-request-topic: user-add-request
        user-add-reply-topic: user-add-reply
        user-find-by-username-request-topic: user-find-by-username-request
        user-find-by-username-reply-topic: user-find-by-username-reply
    consumer:
      group-id: user-group
      properties:
        spring.json.trusted.packages: com.vlz.authservice.dto.event,com.vlz.userservice.dto.event

  spring:
    security:
      jwt:
        public-key-location: classpath:keys/public.pem
        private-key-location: classpath:keys/private.pem
        expiration: 3600000